# Generated by Django 4.2.6 on 2023-12-31 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=12)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('create_date', models.DateTimeField(default=datetime.timezone)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.DateTimeField(default=False)),
                ('is_staff', models.DateTimeField(default=False)),
                ('is_active', models.DateTimeField(default=False)),
                ('is_superadmin', models.DateTimeField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
